### ISSUE TITLE
fofa无法检索 

### ISSUE THREAD

**Issue by lemonlove7** [nex121/fofa_full_search#1]
<img width="1024" alt="image" src="https://github.com/nex121/fofa_full_search/assets/56328995/d54bc2a7-344f-414c-a0c3-2f44ea692334">
<img width="1024" alt="image" src="https://github.com/nex121/fofa_full_search/assets/56328995/e6507e60-232b-4e57-a12a-6a5422683eb7">

**Comment by nex121** [comment]
有没有配置fofa key

**Comment by lemonlove7** [comment]
配置了 win和mac都不行 
java版本：
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
<img width="594" alt="image" src="https://github.com/nex121/fofa_full_search/assets/56328995/c9de574c-8b21-4442-88a5-1efab14368e0">

**Comment by lemonlove7** [comment]
解决了，必须要把fofa和hunter配置好勾选上才行
